### ISSUE TITLE
Only 404 links on generated report

### ISSUE THREAD

**Issue by pacan1** [kootstra/robotframework-allure#6]
I've robotframework(python), allure, and the pytest allure adaptor installed.

**pytest-allure-adaptor (1.7.9)**

**robotframework-allurereport (1.1.1)**

**allure --version 2.4.1**

When I run pybot with the Allure listener an xml file is generated. However running allure generate on this generates an error:

**allure generate --clean**

> Could not read result allure-results/7c28854b-7ac2-497b-89b0-f312427db7db-testsuite.xml: {}
> com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `ru.yandex.qatools.allure.model.SeverityLevel` from String "None": value not one of declared Enum instance names: [trivial, blocker, minor, normal, critical]
>  at [Source: (sun.nio.ch.ChannelInputStream); line: 6, column: 5] (through reference chain: ru.yandex.qatools.allure.model.TestSuiteResult["test-cases"]->java.util.ArrayList[0]->ru.yandex.qatools.allure.model.TestCaseResult["severity"])
>         at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
>         at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1535)
>         at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:910)
>         at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeAltString(EnumDeserializer.java:255)
>         at com.fasterxml.jackson.databind.des

**cd allure-report**
**ls -lrt**

1638751 Nov 17 16:16 styles.css
306 Nov 17 16:16 plugins
647 Nov 17 16:16 index.html
136 Nov 17 16:16 history
860 Nov 17 16:16 favicon.ico
136 Nov 17 16:16 export
374 Nov 17 16:16 data
680472 Nov 17 16:16 app.js

index.html opens but contains all 404 links. Any idea why?

**Comment by ornichola** [comment]
I was able to see proper report using `allure serve <report_folder_with_xmls>`. The report, generated by `allure generate <report_folder_with_xmls> <new_folder>` also shows 404.

**Comment by ghost** [comment]
@ornichola same problem here https://github.com/kootstra/robotframework-allurereport/issues/7
I've described it in my comment
https://github.com/kootstra/robotframework-allurereport/issues/7#issuecomment-355750077
