### ISSUE TITLE
Cannot Import etree when using Maven

### ISSUE THREAD

**Issue by nosebane** [kootstra/robotframework-allure#9]
Hi, I am using robotframework maven plugin to run my test, i have installed Python 3.6 and all allurereports library, but got stuck when importing etree : 

[ ERROR ] Error in file 'D:\Data\Documents\Stash\RobotCWP\src\test\resources\login_resource.robot': Importing test library 'AllureReportLibrary' failed: ImportError: cannot import name etree
Traceback (most recent call last):
  File "C:\Users\E460\AppData\Local\Programs\Python\Python36\Lib\site-packages\AllureReportLibrary\__init__.py", line 1, in <module>
    from .AllureReportLibrary import *
  File "C:\Users\E460\AppData\Local\Programs\Python\Python36\Lib\site-packages\AllureReportLibrary\AllureReportLibrary.py", line 1, in <module>
    from .AllureListener import AllureListener
  File "C:\Users\E460\AppData\Local\Programs\Python\Python36\Lib\site-packages\AllureReportLibrary\AllureListener.py", line 2, in <module>
    from lxml import etree
 

By the way, it work when not using maven, but i need maven to organize the tests,  please help ?

**Comment by ghost** [comment]
Hello.
Are you sure you use Python 3.6 when run robot manually?
As far I know this library doesn't work with Python 3.

**Comment by nosebane** [comment]
Sorry i was using your python3 branch,but i already tried installing pyhton 2.7 also.and use this library and still no luck. i was thinking somehow the lxml is not compatible with robotframework maven plugin

**Comment by alifiaw** [comment]
Hello I'm having the same problem. I checked out python3 branch, execute it with robot : no problem.
But when tried run using maven, I had error. Here's my pom.xml

> <build>
        <plugins>
            <plugin>
                <groupId>org.robotframework</groupId>
                <artifactId>robotframework-maven-plugin</artifactId>
                <version>1.4.7</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>run</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>io.qameta.allure</groupId>
                <artifactId>allure-maven</artifactId>
                <version>2.8</version>
                <configuration>
                    <reportVersion>2.3.1</reportVersion>
                    <propertiesFilePath>target/robotframework-reports/allure</propertiesFilePath>
                    <reportDirectory>allure-report</reportDirectory>
                </configuration>
            </plugin>
        </plugins>
    </build>

Here's the error I got

> [ ERROR ] Error in file 'D:\Data\Documents\xbaseauto\src\test\resources\login_resource.robot': Importing test library 'AllureReportLibrary' failed: AttributeError: 'module' object has no attribute 'pythonapi'
Traceback (most recent call last):
  File "...\site-packages\attr\_compat.py", line 131, in make_set_closure_cell
    set_closure_cell = ctypes.pythonapi.PyCell_Set

Any idea how to solve this? Thanks in advance

**Comment by simplyviks** [comment]
i am also facing the same issue, one point here is lxml is a cython module , may be that's the problem.?

raceback (most recent call last): File "XXXXX" line 3, in <module> from lxml import etree PYTHONPATH:
